/**
 * Section Library — Shared Types
 *
 * Each section variant is a pre-built, validated SDUI JSON template.
 * Slot markers use [[SLOT_NAME]] syntax (double brackets) to avoid
 * collision with SDUI runtime interpolation {{state.path}}.
 */

// ─── Slot system ─────────────────────────────────────────────────────────────

/** Slot marker format: [[SLOT_NAME]] — replaced at instantiation time */
export type SlotName = string;

/** Params provided by the AI to fill [[SLOT_NAME]] markers */
export type SectionParams = Record<SlotName, string>;

// ─── Section variant ──────────────────────────────────────────────────────────

export interface SectionVariantMeta {
  /** Unique identifier: "{sectionType}.{variantName}" */
  variantId: string;
  /** Human-readable label */
  label: string;
  /** Design moods this variant suits best */
  bestFor: string[];
  /** Required [[SLOT_NAME]] markers that must be filled */
  requiredSlots: SlotName[];
  /** Optional [[SLOT_NAME]] markers with defaults */
  optionalSlots: SlotName[];
  /** Default values for optional slots */
  slotDefaults?: Record<SlotName, string>;
  /** State paths this section reads — used to build prebuiltState + initActions */
  statePaths?: string[];
  /** initAction keys this section needs */
  initActions?: string[];
}

export interface SectionVariant {
  _meta: SectionVariantMeta;
  /** SDUI node tree — may contain [[SLOT_NAME]] markers */
  node: Record<string, unknown>;
}

// ─── Manifest entry (compact — what the AI reads) ────────────────────────────

export interface ManifestEntry {
  variantId: string;
  label: string;
  bestFor: string[];
  requiredSlots: SlotName[];
  optionalSlots: SlotName[];
}

// ─── Structure agent output (new compact format) ─────────────────────────────

export interface SectionSelection {
  variantId: string;
  params?: SectionParams;
}

export interface StructureAgentCompactOutput {
  /** Navbar SDUI node (still generated by AI — complex, brand-specific) */
  navbar: Record<string, unknown>;
  /** Footer SDUI node (still generated by AI) */
  footer: Record<string, unknown>;
  /** Ordered list of section selections */
  sections: SectionSelection[];
}
