'use client';

/**
 * _workflow-styles.ts
 *
 * CSS-in-JS style object `S` for the WorkflowCanvas dark theme.
 * Extracted from _workflow-canvas.tsx to keep styles separate from component logic.
 * All components in the workflow canvas import S from here.
 */

// ─── Canvas dark-theme style constants ────────────────────────────────────────
// Palette: #1a1a2e canvas, #0f172a top bar, #111827 panels, #1e293b cards

export const S = {
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    zIndex: 9999,
    background: '#0f172a',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 16px',
    height: 48,
    borderBottom: '1px solid #1f2937',
    background: '#0f172a',
    flexShrink: 0,
    gap: 12,
  },
  tabPill: (active: boolean) => ({
    padding: '4px 14px',
    borderRadius: 20,
    background: active ? '#1d4ed8' : 'transparent',
    color: active ? '#fff' : '#9ca3af',
    fontSize: 13,
    fontWeight: 500,
    border: 'none',
    cursor: 'pointer',
  }),
  closeBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontSize: 13,
    color: '#9ca3af',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: 6,
  },
  contentArea: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  canvasArea: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative' as const,
    background: '#1a1a2e',
    cursor: 'default',
  },
  flowColumn: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: 0,
    minWidth: 280,
  },
  vLine: {
    width: 1,
    height: 16,
    background: '#374151',
    flexShrink: 0,
  },
  arrowHead: {
    width: 0,
    height: 0,
    borderLeft: '4px solid transparent',
    borderRight: '4px solid transparent',
    borderTop: '6px solid #374151',
    flexShrink: 0,
  },
  insertBtn: (hovered: boolean) => ({
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: `1px solid ${hovered ? '#3b82f6' : '#374151'}`,
    background: hovered ? '#1e3a5f' : '#1e293b',
    color: hovered ? '#3b82f6' : '#6b7280',
    fontSize: 14,
    lineHeight: '18px',
    textAlign: 'center' as const,
    cursor: 'pointer',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  }),
  card: (selected: boolean, incomplete: boolean) => ({
    width: 280,
    background: '#1e293b',
    border: `1px solid ${selected ? '#3b82f6' : '#374151'}`,
    borderRadius: 12,
    padding: '12px 14px',
    cursor: 'pointer',
    boxShadow: selected ? '0 0 0 3px rgba(59,130,246,0.2)' : '0 1px 4px rgba(0,0,0,0.3)',
    flexShrink: 0,
    userSelect: 'none' as const,
  }),
  cardTopRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  cardIcon: {
    fontSize: 13,
    color: '#9ca3af',
    flexShrink: 0,
  },
  cardName: {
    flex: 1,
    fontSize: 13,
    fontWeight: 600,
    color: '#f3f4f6',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  cardSubtext: (incomplete: boolean) => ({
    fontSize: 11,
    color: incomplete ? '#f59e0b' : '#6b7280',
    marginTop: 2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  }),
  testBtn: (disabled: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    fontSize: 11,
    color: disabled ? '#374151' : '#9ca3af',
    background: 'none',
    border: `1px solid ${disabled ? '#1f2937' : '#374151'}`,
    borderRadius: 5,
    padding: '2px 7px',
    cursor: disabled ? 'default' : 'pointer',
    flexShrink: 0,
  }),
  moreBtn: {
    background: 'none',
    border: 'none',
    color: '#6b7280',
    cursor: 'pointer',
    fontSize: 16,
    padding: '0 2px',
    lineHeight: 1,
    flexShrink: 0,
  },
  pillNode: (selected: boolean, dashed?: boolean) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 16px',
    borderRadius: 24,
    border: `${dashed ? '2px dashed' : '1px solid'} ${selected ? '#3b82f6' : '#374151'}`,
    background: '#1e293b',
    fontSize: 13,
    fontWeight: 500,
    color: '#e5e7eb',
    cursor: 'pointer',
    boxShadow: selected ? '0 0 0 3px rgba(59,130,246,0.2)' : '0 1px 4px rgba(0,0,0,0.3)',
    userSelect: 'none' as const,
    flexShrink: 0,
  }),
  branchHLine: (width: number) => ({
    width,
    height: 1,
    background: '#374151',
    flexShrink: 0,
  }),
  branchRejoin: (width: number) => ({
    width,
    height: 16,
    borderBottom: '1px solid #374151',
    borderLeft: '1px solid #374151',
    borderRight: '1px solid #374151',
    borderRadius: '0 0 8px 8px',
    flexShrink: 0,
  }),
  loopContainer: {
    borderRadius: 12,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: 0,
    position: 'relative' as const,
    minWidth: 312,
    paddingLeft: 24,
    paddingRight: 24,
  },
  endLoopLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: '#9ca3af',
    background: '#1e293b',
    border: '1px solid #374151',
    borderRadius: 6,
    padding: '4px 12px',
  },
  addActionLink: {
    fontSize: 12,
    fontWeight: 600,
    color: '#9ca3af',
    cursor: 'pointer',
    background: 'rgba(107,114,128,0.10)',
    border: '1px solid rgba(107,114,128,0.25)',
    borderRadius: 20,
    padding: '4px 14px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  triggerPill: (clickable: boolean) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 18px',
    borderRadius: 24,
    border: '1px solid #374151',
    background: '#1e293b',
    fontSize: 13,
    fontWeight: 500,
    color: clickable ? '#e5e7eb' : '#6b7280',
    cursor: clickable ? 'pointer' : 'default',
    boxShadow: '0 1px 4px rgba(0,0,0,0.3)',
    userSelect: 'none' as const,
    position: 'relative' as const,
  }),
  rightPanel: {
    width: 288,
    borderLeft: '1px solid #1f2937',
    background: '#111827',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
    flexShrink: 0,
  },
  rightPanelHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    borderBottom: '1px solid #1f2937',
    flexShrink: 0,
  },
  rightPanelBody: {
    flex: 1,
    overflow: 'auto',
    padding: '12px',
  },
  fieldLabel: {
    fontSize: 11,
    color: '#9ca3af',
    marginBottom: 4,
    marginTop: 10,
    display: 'block',
  },
  fieldInput: {
    width: '100%',
    fontSize: 12,
    padding: '6px 8px',
    border: '1px solid #374151',
    borderRadius: 6,
    color: '#f3f4f6',
    background: '#1e293b',
    boxSizing: 'border-box' as const,
    outline: 'none',
  },
  fieldSelect: {
    width: '100%',
    fontSize: 12,
    padding: '6px 8px',
    border: '1px solid #374151',
    borderRadius: 6,
    color: '#f3f4f6',
    background: '#1e293b',
    boxSizing: 'border-box' as const,
    appearance: 'none' as const,
  },
  toggleGroup: {
    display: 'flex',
    border: '1px solid #374151',
    borderRadius: 6,
    overflow: 'hidden',
  },
  toggleBtn: (active: boolean) => ({
    flex: 1,
    padding: '5px 0',
    background: active ? '#1f2937' : 'transparent',
    border: 'none',
    fontSize: 12,
    color: active ? '#f3f4f6' : '#6b7280',
    cursor: 'pointer',
    fontWeight: active ? 600 : 400,
  }),
  dropdown: {
    position: 'absolute' as const,
    top: '100%',
    left: 0,
    zIndex: 100,
    background: '#1f2937',
    border: '1px solid #374151',
    borderRadius: 10,
    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
    minWidth: 240,
    maxHeight: 360,
    overflow: 'auto',
    marginTop: 4,
  },
  dropdownSearch: {
    width: '100%',
    padding: '8px 12px',
    border: 'none',
    borderBottom: '1px solid #374151',
    fontSize: 12,
    color: '#f3f4f6',
    background: 'transparent',
    boxSizing: 'border-box' as const,
    outline: 'none',
  },
  dropdownCategory: {
    fontSize: 10,
    fontWeight: 600,
    color: '#6b7280',
    textTransform: 'uppercase' as const,
    padding: '8px 12px 4px',
    letterSpacing: '0.05em',
  },
  dropdownItem: (active: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '7px 12px',
    fontSize: 12,
    color: '#e5e7eb',
    background: active ? '#1d4ed8' : 'transparent',
    cursor: 'pointer',
    border: 'none',
    width: '100%',
    textAlign: 'left' as const,
  }),
  contextMenu: {
    position: 'fixed' as const,
    background: '#1f2937',
    border: '1px solid #374151',
    borderRadius: 8,
    boxShadow: '0 4px 20px rgba(0,0,0,0.5)',
    zIndex: 10000,
    minWidth: 180,
    overflow: 'hidden',
  },
  contextItem: (danger?: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '7px 14px',
    fontSize: 12,
    color: danger ? '#f87171' : '#e5e7eb',
    cursor: 'pointer',
    background: 'transparent',
    border: 'none',
    width: '100%',
    textAlign: 'left' as const,
  }),
  bottomBar: {
    position: 'absolute' as const,
    bottom: 16,
    right: 16 + 288 + 8,
    display: 'flex',
    gap: 4,
  },
  zoomBtn: {
    width: 32,
    height: 32,
    background: '#1e293b',
    border: '1px solid #374151',
    borderRadius: 6,
    fontSize: 16,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 1px 4px rgba(0,0,0,0.3)',
    color: '#e5e7eb',
  },
  infoBox: {
    background: '#1e3a5f',
    border: '1px solid #1d4ed8',
    borderRadius: 6,
    padding: '5px 8px',
    fontSize: 11,
    color: '#93c5fd',
    lineHeight: 1.4,
    marginTop: 8,
  },
  helpText: {
    fontSize: 11,
    color: '#6b7280',
    lineHeight: 1.5,
    marginTop: 8,
    background: '#1f2937',
    border: '1px solid #374151',
    borderRadius: 6,
    padding: '8px 10px',
  },
  warnBox: {
    background: '#451a03',
    border: '1px solid #92400e',
    borderRadius: 6,
    padding: '6px 10px',
    fontSize: 11,
    color: '#fbbf24',
    marginTop: 4,
  },
};
