'use client';

/**
 * _workflow-styles.ts
 *
 * CSS-in-JS style object `S` for the WorkflowCanvas dark theme.
 * Extracted from _workflow-canvas.tsx to keep styles separate from component logic.
 * All components in the workflow canvas import S from here.
 */

// ─── Canvas dark-theme style constants ────────────────────────────────────────
// Palette: var(--bld-bg-canvas) canvas, var(--bld-bg-base) top bar, var(--bld-bg-panel) panels, var(--bld-bg-elevated) cards

export const S = {
  overlay: {
    position: 'fixed' as const,
    inset: 0,
    zIndex: 9999,
    background: 'var(--bld-bg-base)',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 16px',
    height: 48,
    borderBottom: 'none',
    background: 'var(--bld-bg-base)',
    flexShrink: 0,
    gap: 12,
  },
  tabPill: (active: boolean) => ({
    padding: '4px 14px',
    borderRadius: 20,
    background: active ? 'var(--bld-accent-hover)' : 'transparent',
    color: active ? 'var(--bld-accent-fg)' : 'var(--bld-text-3)',
    fontSize: 13,
    fontWeight: 500,
    border: 'none',
    cursor: 'pointer',
  }),
  closeBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontSize: 13,
    color: 'var(--bld-text-3)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: 6,
  },
  contentArea: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  canvasArea: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative' as const,
    background: 'var(--bld-bg-canvas)',
    cursor: 'default',
  },
  flowColumn: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: 0,
    minWidth: 280,
  },
  vLine: {
    width: 1,
    height: 16,
    background: 'var(--bld-border-subtle)',
    flexShrink: 0,
  },
  arrowHead: {
    width: 0,
    height: 0,
    borderLeft: '4px solid transparent',
    borderRight: '4px solid transparent',
    borderTop: '6px solid var(--bld-border-subtle)',
    flexShrink: 0,
  },
  insertBtn: (hovered: boolean) => ({
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: `1px solid ${hovered ? 'var(--bld-accent)' : 'var(--bld-border-subtle)'}`,
    background: hovered ? 'var(--bld-bg-elevated)' : 'var(--bld-bg-elevated)',
    color: hovered ? 'var(--bld-accent)' : 'var(--bld-text-disabled)',
    fontSize: 14,
    lineHeight: '18px',
    textAlign: 'center' as const,
    cursor: 'pointer',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  }),
  card: (selected: boolean, incomplete: boolean) => ({
    width: 280,
    background: 'var(--bld-bg-elevated)',
    border: `1px solid ${selected ? 'var(--bld-accent)' : 'var(--bld-border-subtle)'}`,
    borderRadius: 12,
    padding: '12px 14px',
    cursor: 'pointer',
    boxShadow: selected ? '0 0 0 3px rgba(59,130,246,0.2)' : '0 1px 4px rgba(0,0,0,0.3)',
    flexShrink: 0,
    userSelect: 'none' as const,
  }),
  cardTopRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  cardIcon: {
    fontSize: 13,
    color: 'var(--bld-text-3)',
    flexShrink: 0,
  },
  cardName: {
    flex: 1,
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--bld-text-1)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  cardSubtext: (incomplete: boolean) => ({
    fontSize: 11,
    color: incomplete ? 'var(--bld-warning)' : 'var(--bld-text-disabled)',
    marginTop: 2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  }),
  testBtn: (disabled: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    fontSize: 11,
    color: disabled ? 'var(--bld-border-subtle)' : 'var(--bld-text-3)',
    background: 'none',
    border: `1px solid ${disabled ? 'var(--bld-bg-input)' : 'var(--bld-border-subtle)'}`,
    borderRadius: 5,
    padding: '2px 7px',
    cursor: disabled ? 'default' : 'pointer',
    flexShrink: 0,
  }),
  moreBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--bld-text-disabled)',
    cursor: 'pointer',
    fontSize: 16,
    padding: '0 2px',
    lineHeight: 1,
    flexShrink: 0,
  },
  pillNode: (selected: boolean, dashed?: boolean) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 16px',
    borderRadius: 24,
    border: `${dashed ? '2px dashed' : '1px solid'} ${selected ? 'var(--bld-accent)' : 'var(--bld-border-subtle)'}`,
    background: 'var(--bld-bg-elevated)',
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--bld-text-2)',
    cursor: 'pointer',
    boxShadow: selected ? '0 0 0 3px rgba(59,130,246,0.2)' : '0 1px 4px rgba(0,0,0,0.3)',
    userSelect: 'none' as const,
    flexShrink: 0,
  }),
  branchHLine: (width: number) => ({
    width,
    height: 1,
    background: 'var(--bld-border-subtle)',
    flexShrink: 0,
  }),
  branchRejoin: (width: number) => ({
    width,
    height: 16,
    borderBottom: '1px solid var(--bld-border-subtle)',
    borderLeft: '1px solid var(--bld-border-subtle)',
    borderRight: '1px solid var(--bld-border-subtle)',
    borderRadius: '0 0 8px 8px',
    flexShrink: 0,
  }),
  loopContainer: {
    borderRadius: 12,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: 0,
    position: 'relative' as const,
    minWidth: 312,
    paddingLeft: 24,
    paddingRight: 24,
  },
  endLoopLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--bld-text-3)',
    background: 'var(--bld-bg-elevated)',
    border: '1px solid var(--bld-border-subtle)',
    borderRadius: 6,
    padding: '4px 12px',
  },
  addActionLink: {
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--bld-text-3)',
    cursor: 'pointer',
    background: 'rgba(107,114,128,0.10)',
    border: '1px solid rgba(107,114,128,0.25)',
    borderRadius: 20,
    padding: '4px 14px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  triggerPill: (clickable: boolean) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 18px',
    borderRadius: 24,
    border: '1px solid var(--bld-border-subtle)',
    background: 'var(--bld-bg-elevated)',
    fontSize: 13,
    fontWeight: 500,
    color: clickable ? 'var(--bld-text-2)' : 'var(--bld-text-disabled)',
    cursor: clickable ? 'pointer' : 'default',
    boxShadow: '0 1px 4px rgba(0,0,0,0.3)',
    userSelect: 'none' as const,
    position: 'relative' as const,
  }),
  rightPanel: {
    width: 288,
    borderLeft: '1px solid var(--bld-bg-input)',
    background: 'var(--bld-bg-panel)',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
    flexShrink: 0,
  },
  rightPanelHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    borderBottom: 'none',
    flexShrink: 0,
  },
  rightPanelBody: {
    flex: 1,
    overflow: 'auto',
    padding: '12px',
  },
  fieldLabel: {
    fontSize: 11,
    color: 'var(--bld-text-3)',
    marginBottom: 4,
    marginTop: 10,
    display: 'block',
  },
  fieldInput: {
    width: '100%',
    fontSize: 12,
    padding: '6px 8px',
    border: '1px solid var(--bld-border-subtle)',
    borderRadius: 6,
    color: 'var(--bld-text-1)',
    background: 'var(--bld-bg-elevated)',
    boxSizing: 'border-box' as const,
    outline: 'none',
  },
  fieldSelect: {
    width: '100%',
    fontSize: 12,
    padding: '6px 8px',
    border: '1px solid var(--bld-border-subtle)',
    borderRadius: 6,
    color: 'var(--bld-text-1)',
    background: 'var(--bld-bg-elevated)',
    boxSizing: 'border-box' as const,
    appearance: 'none' as const,
  },
  toggleGroup: {
    display: 'flex',
    border: '1px solid var(--bld-border-subtle)',
    borderRadius: 6,
    overflow: 'hidden',
  },
  toggleBtn: (active: boolean) => ({
    flex: 1,
    padding: '5px 0',
    background: active ? 'var(--bld-bg-input)' : 'transparent',
    border: 'none',
    fontSize: 12,
    color: active ? 'var(--bld-text-1)' : 'var(--bld-text-disabled)',
    cursor: 'pointer',
    fontWeight: active ? 600 : 400,
  }),
  dropdown: {
    position: 'absolute' as const,
    top: '100%',
    left: 0,
    zIndex: 100,
    background: 'var(--bld-bg-input)',
    border: '1px solid var(--bld-border-subtle)',
    borderRadius: 10,
    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
    minWidth: 240,
    maxHeight: 360,
    overflow: 'auto',
    marginTop: 4,
  },
  dropdownSearch: {
    width: '100%',
    padding: '8px 12px',
    border: 'none',
    borderBottom: '1px solid var(--bld-border-subtle)',
    fontSize: 12,
    color: 'var(--bld-text-1)',
    background: 'transparent',
    boxSizing: 'border-box' as const,
    outline: 'none',
  },
  dropdownCategory: {
    fontSize: 10,
    fontWeight: 600,
    color: 'var(--bld-text-disabled)',
    textTransform: 'none' as const,
    padding: '8px 12px 4px',
    background: 'var(--bld-bg-input)',
  },
  dropdownItem: (active: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '7px 12px',
    fontSize: 12,
    color: 'var(--bld-text-2)',
    background: active ? 'var(--bld-accent-hover)' : 'var(--bld-bg-input)',
    cursor: 'pointer',
    border: 'none',
    width: '100%',
    textAlign: 'left' as const,
  }),
  contextMenu: {
    position: 'fixed' as const,
    background: 'var(--bld-bg-input)',
    border: '1px solid var(--bld-border-subtle)',
    borderRadius: 8,
    boxShadow: '0 4px 20px rgba(0,0,0,0.5)',
    zIndex: 10000,
    minWidth: 180,
    overflow: 'hidden',
  },
  contextItem: (danger?: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '7px 14px',
    fontSize: 12,
    color: danger ? 'var(--bld-error)' : 'var(--bld-text-2)',
    cursor: 'pointer',
    background: 'transparent',
    border: 'none',
    width: '100%',
    textAlign: 'left' as const,
  }),
  bottomBar: {
    position: 'absolute' as const,
    bottom: 16,
    right: 16 + 288 + 8,
    display: 'flex',
    gap: 4,
  },
  zoomBtn: {
    width: 32,
    height: 32,
    background: 'var(--bld-bg-elevated)',
    border: '1px solid var(--bld-border-subtle)',
    borderRadius: 6,
    fontSize: 16,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 1px 4px rgba(0,0,0,0.3)',
    color: 'var(--bld-text-2)',
  },
  infoBox: {
    background: 'var(--bld-bg-elevated)',
    border: '1px solid var(--bld-accent-hover)',
    borderRadius: 6,
    padding: '5px 8px',
    fontSize: 11,
    color: 'var(--bld-accent)',
    lineHeight: 1.4,
    marginTop: 8,
  },
  helpText: {
    fontSize: 11,
    color: 'var(--bld-text-disabled)',
    lineHeight: 1.5,
    marginTop: 8,
    background: 'var(--bld-bg-input)',
    border: '1px solid var(--bld-border-subtle)',
    borderRadius: 6,
    padding: '8px 10px',
  },
  warnBox: {
    background: 'rgba(245,158,11,0.12)',
    border: '1px solid var(--bld-warning)',
    borderRadius: 6,
    padding: '6px 10px',
    fontSize: 11,
    color: 'var(--bld-warning)',
    marginTop: 4,
  },
};
