/**
 * Phase H — ContractManifest types. The Planner emits a manifest mapping each
 * resolved Operation to the agents that will satisfy it; downstream agents
 * receive only the slices relevant to their op-id.
 *
 * The manifest is the single source of truth for:
 *  - which agents run (per-op)
 *  - the dispatch order (parallel within an op, sequential across ops)
 */

export type AgentScope = 'structure' | 'media' | 'styling' | 'animation' | 'workflows' | 'binding' | 'data' | 'sharedComponents';

export interface ManifestOperation {
  id: string;
  summary: string;
  /** Page route this op targets (e.g. "/", "/about"). Used by the pool builder to assign
   *  depth-1 section chunks to the correct styling/animation agent pair. */
  pageRoute?: string;
  /** Human-readable page name matching pageRoute (e.g. "Landing", "Pricing"). Set by Planner. */
  pageName?: string;
  /** Resolved node IDs (from selection or planner). May be empty for new-creation ops. */
  resolvedNodeIds: string[];
  /** Per-agent contract — the tools & inputs the agent is permitted to use for this op. */
  agents: Partial<Record<AgentScope, AgentContract>>;
}

export interface AgentContract {
  /** Free-form instructions the orchestrator wants the agent to follow. */
  briefing?: string;
  /** Optional payload pre-built by the planner (variable IDs, route hints, etc.). */
  context?: Record<string, unknown>;
}

export interface SharedComponentDefinition {
  id: string;
  name: string;
  description?: string;
  /** REQUIRED — planner authors full internal node tree inline. Structure step stamps _sharedKey on any node missing one. */
  content: unknown;
  properties?: Array<{
    id: string;
    name: string;
    type: string;
    defaultValue?: unknown;
    options?: Array<{ label: string; value: string }>;
  }>;
  variables?: Record<string, { label: string; type: string; initialValue: unknown }>;
  formulas?: Record<string, { id: string; name: string; params: unknown[]; formula: string }>;
  workflows?: Record<string, { id: string; name: string; trigger: string; params: unknown[]; steps: unknown[] }>;
  triggers?: Array<{ id: string; name: string; payload?: unknown }>;
  valueVariable?: string;
}

export interface ContractManifest {
  /** Global summary used in the assistant's reply text. */
  intent: string;
  /** Detailed, expanded version of the user's request written in plain UI language.
   *  Generated by the planner so all specialist agents share the same rich spec
   *  instead of each interpreting the raw vague message independently.
   *  For "create apple calculator" this would describe layout, colors, button labels,
   *  interactions, etc. For already-detailed requests it is a cleaned-up restatement. */
  refinedRequest?: string;
  /** Set by the planner when the request is ambiguous. If set, no agents run — the
   *  question is returned to the user instead. */
  needsClarification?: { question: string; options?: string[] } | null;
  operations: ManifestOperation[];
  /**
   * Shared component models to create before the parallel agent pool starts.
   * The planner authors full inline content — no shell + SC-author agent pattern.
   * Structure step processes these BEFORE pages, stamps _sharedKey on internal nodes,
   * so all three instance-override paths work immediately when specialists start.
   */
  sharedComponentsToCreate?: SharedComponentDefinition[];
}

export function findAgentContract(
  manifest: ContractManifest,
  opId: string,
  agent: AgentScope,
): AgentContract | undefined {
  return manifest.operations.find(o => o.id === opId)?.agents[agent];
}

