/**
 * Structure Agent — gpt-4o
 *
 * Builds the full SDUI page in one call: content sections + navbar + footer.
 * Receives pre-built content and theme — NEVER invents copy or images.
 * Generates layoutParts.navbar.structure and layoutParts.footer.structure
 * so no separate navbar agent is needed.
 *
 * Accepts optional retryFeedback from ValidatorAgent or QAReviewerAgent.
 *
 * NEW: Also exports runStructureAgentCompact() which uses the section library
 * manifest — the AI picks variant IDs and params instead of generating full JSON.
 */

import { generateText, generateObject, Output } from 'ai';
import { openai } from '@ai-sdk/openai';
import { z } from 'zod';
import {
  buildSduiReference,
  buildThemeContext,
} from '@/lib/ai/sdui-config-context';
import { buildDesignPrinciplesContext } from '@/lib/ai/design-principles';
import { buildTechPatternsContext } from '@/lib/ai/tech-patterns';
import { buildCorrectionsContext } from '@/lib/ai/eval/corrections-builder';
import { buildFewShotExamples } from '@/lib/ai/eval/few-shot-examples';
import type { DesignBrief } from './brief-agent';
import type { GeneratedContent } from './content-agent';
import type { DesignSpec } from './design-director-agent';
import type { Palette } from '@/lib/ai/palette-schema';
import type { FontPairing } from '@/lib/ai/font-pairing-schema';
import { pageGeneratorOutputSchema, type PageGeneratorOutput } from '@/lib/ai/page-generator';
import { buildManifestContext } from '@/lib/ai/section-library/manifest';
import type { SectionSelection } from '@/lib/ai/section-library/types';

// ─── Retry context ────────────────────────────────────────────────────────────

export interface StructureRetryContext {
  validatorErrors?: string[];
  qaIssues?: Array<{
    section: string;
    severity: 'critical' | 'minor';
    description: string;
    fix: string;
  }>;
}

// ─── Navbar rules ─────────────────────────────────────────────────────────────

const NAVBAR_RULES = `NAVBAR RULES (generate layoutParts.navbar.structure):
- Root node: the root MUST have "id": "navbar-root" as a top-level JSON field (NOT inside props), and props.className includes "fixed top-0 left-0 right-0 z-50 w-full"
  Example: { "type": "Box", "id": "navbar-root", "props": { "className": "fixed top-0 left-0 right-0 z-50 w-full bg-[var(--theme-header-bg)]" }, ... }
- CRITICAL: Box defaults to flex-col. The inner navbar wrapper MUST have "flex-row" to lay items horizontally:
  Example: { "type": "Box", "props": { "className": "w-full max-w-7xl mx-auto px-6 py-3 flex flex-row justify-between items-center" }, ... }
  WITHOUT "flex-row" the brand, nav links, and icons STACK VERTICALLY — broken navbar.
- Colors: use var(--theme-header-bg), var(--theme-header-text), var(--theme-header-border) — NEVER hardcode hex
- Required child IDs: navbar-inner, navbar-row, navbar-left, navbar-right, navbar-actions, navbar-cart, navbar-auth
- Brand logo: ALWAYS a Text or Heading node with brand name — NEVER NextImage with local paths (e.g. /brand-logo.svg does not exist)
  Example: { "type": "Heading", "props": { "size": "lg", "className": "font-bold text-[var(--theme-header-text)]" }, "text": "BrandName" }
- Nav links: map over featured.categories from page state — NOT nav.collections (that fetches the generic Vendure demo store categories: Electronics/Home & Garden which are WRONG for your brand)
  The brand-specific categories are in featured.categories, generated by the Content Agent.
  Example: { "type": "Box", "id": "navbar-row", "props": { "className": "hidden md:flex flex-row items-center gap-6" }, "children": [
    { "type": "Pressable", "map": "featured.categories", "key": "$item.id",
      "actions": { "click": { "action": "navigate", "payload": { "routeConfig": "collection", "slug": "{{$item.slug}}" } } },
      "children": [{ "type": "Text", "props": { "className": "text-[var(--theme-header-text)] text-sm font-medium hover:opacity-70" }, "text": "{{$item.name}}" }]
    }
  ]}
- Cart icon: NavIcon with icon "ShoppingBag" inside a relative Pressable
  Badge condition: { ">": [{ "var": ["cart.totalQuantity", 0] }, 0] }
  Badge text: { "expr": { "var": "cart.totalQuantity" } }
  Badge className: absolute -top-0.5 -right-0.5 h-3.5 w-3.5 pointer-events-none rounded-full bg-[var(--theme-shop-button)] flex items-center justify-center
- Theme toggle: button id="navbar-theme" with action toggleThemeMenu; dropdown with condition { "var": "nav.themeMenuOpen" }
  Backdrop: condition { "var": "nav.themeMenuOpen" }, action closeThemeMenu
  Menu items use actions: setThemeLight, setThemeDark, setThemeSystem
- Auth: condition { "==": [{ "var": "auth.user" }, null] } for Sign In link; { "!=": ... } for logged-in state
- Icons: { "type": "NavIcon", "props": { "icon": "Search", "size": 20 } } — NEVER { "type": "Icon", "props": { "as": "SearchIcon" } }
- Layout actions: toggleThemeMenu, closeThemeMenu, setThemeLight, setThemeDark, setThemeSystem, goToCart, logout
- No $ref in output — everything inline
- Pressable/Box: NEVER raw text — always wrap in Text child
- actions format: ALWAYS a record { "click": {...} } — NEVER an array
- Button with label: ALWAYS use ButtonText child, never use "text" directly on Button
  Example: { "type": "Button", "children": [{ "type": "ButtonText", "text": "Shop Now" }] }`;

// ─── Footer rules ─────────────────────────────────────────────────────────────

const FOOTER_RULES = `FOOTER RULES (generate layoutParts.footer.structure):
- Root node: id="footer-root", w-full bg-[var(--theme-footer-bg)]
- Text colors: text-[var(--theme-footer-text)] for primary, text-[var(--theme-footer-textMuted)] for secondary/muted
- Include: brand name (Heading), short tagline or brand personality phrase, category links from the pre-built state, copyright line
- CRITICAL: map over "featured.categories" (screen state) — NOT "nav.collections" (live store, wrong industry)
  Map pattern: the map goes on the LINK ITEM (the Pressable), NOT on the flex-wrap container.
  CORRECT: { "type": "Box", "props": { "className": "flex flex-row flex-wrap gap-4 justify-center" }, "children": [{ "type": "Pressable", "map": "featured.categories", "key": "$item.id", "actions": { "click": { "action": "navigate", "payload": { "routeConfig": "collection", "slug": "{{$item.slug}}" } } }, "children": [{ "type": "Text", "props": { "className": "text-[var(--theme-footer-text)]" }, "text": "{{$item.name}}" }] }] }
  WRONG: { "type": "Box", "map": "featured.categories", "props": { "className": "flex flex-wrap gap-4" }, ... } ← N separate flex-wrap rows
- Copyright: "© 2025 BrandName. All rights reserved." — use the actual brand name from the brief
- Layout: MUST add "flex-row" explicitly for horizontal layouts — Box defaults to flex-col
- No $ref in output — everything inline
- Pressable/Box: NEVER raw text — always wrap in Text child
- All containers spanning full width: include w-full`;

// ─── Section layout templates (injected only for sections in the brief) ───────

function buildSectionTemplates(sections: string[], spec: DesignSpec): string {
  const parts: string[] = [];

  const hasProducts = sections.includes('product-grid') || sections.includes('product-carousel') || sections.includes('flash-sale');
  const hasCategories = sections.includes('featured-categories');
  const hasNewsletter = sections.includes('newsletter');
  const hasTestimonials = sections.includes('testimonials');
  const hasFeatures = sections.includes('features-grid');

  if (hasProducts) {
    const layout = spec.productGridLayout ?? 'uniform-4col';
    if (layout === 'uniform-4col') {
      parts.push(`PRODUCT GRID — uniform-4col: Container "grid grid-cols-4 gap-6 w-full max-w-6xl mx-auto px-4". Map child has className "contents". Each card: Pressable > Box "relative w-full h-52" (NextImage fill) + Box "p-3 flex flex-col gap-1" (productName Text + formatCurrency Text). Card outer: "flex flex-col rounded-xl overflow-hidden shadow-sm bg-[var(--theme-shop-bg)] hover:shadow-md transition-shadow".`);
    } else if (layout === 'featured-3col') {
      parts.push(`PRODUCT GRID — featured-3col: Container "grid grid-cols-3 gap-6 w-full max-w-6xl mx-auto px-4". Use 3 products total. First product card gets className "col-span-2" and taller image "h-72". Remaining 2 cards get "col-span-1" and image "h-52". Each card: Pressable > Box "relative w-full h-52|h-72" (NextImage fill) + Box "p-3 flex flex-col gap-1" (productName + formatCurrency). Card outer: "flex flex-col rounded-xl overflow-hidden shadow-sm bg-[var(--theme-shop-bg)]".`);
    } else if (layout === 'horizontal-cards') {
      parts.push(`PRODUCT GRID — horizontal-cards (catalog/editorial): Container "flex flex-col gap-4 w-full max-w-4xl mx-auto px-4". Map child is a full-width card: "flex flex-row gap-0 rounded-xl overflow-hidden shadow-sm bg-[var(--theme-shop-bg)] hover:shadow-md transition-shadow". Inside: image Box "relative w-40 h-32 flex-none" (NextImage fill object-cover) + text Box "flex-1 p-4 flex flex-col justify-center gap-1" (productName font-semibold + formatCurrency). Wrap in Pressable for navigation.`);
    }
  }

  if (hasCategories) {
    const layout = spec.categoryLayout ?? 'overlay-4col';
    if (layout === 'overlay-4col') {
      parts.push(`CATEGORY SECTION — overlay-4col: Container "grid grid-cols-4 gap-4 w-full max-w-6xl mx-auto px-4". Map child "contents". Each item: Pressable "block rounded-xl overflow-hidden hover:opacity-90" > Box "relative w-full h-48" > NextImage fill + gradient overlay "absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" + Box "absolute bottom-0 left-0 right-0 p-3" > Text "text-white font-bold text-base text-center" "{{$item.name}}".`);
    } else if (layout === 'asymmetric-hero') {
      parts.push(`CATEGORY SECTION — asymmetric-hero: Do NOT use map — access categories by index. Container "flex flex-row gap-4 w-full max-w-6xl mx-auto px-4 h-96". Left: Pressable "flex-1 relative rounded-xl overflow-hidden" with navigate to featured.categories[0].slug > NextImage fill src="{{featured.categories[0].imageUrl}}" + overlay + Text "{{featured.categories[0].name}}". Right: Box "flex-1 flex flex-col gap-4" containing 2 Pressables each "flex-1 relative rounded-xl overflow-hidden" using featured.categories[1] and featured.categories[2].`);
    } else if (layout === 'minimal-strip') {
      parts.push(`CATEGORY SECTION — minimal-strip (refined/luxury): Container "flex flex-row justify-center gap-12 flex-wrap w-full max-w-5xl mx-auto px-4". Map child: Pressable "flex flex-col items-center gap-3 hover:opacity-80 transition-opacity" > Box "relative w-28 h-28 rounded-full overflow-hidden border-2 border-[var(--theme-shop-button)]" (NextImage fill) + Text "text-[var(--theme-content-text)] font-medium text-sm tracking-wide text-center" "{{$item.name}}".`);
    }
  }

  if (hasNewsletter) {
    const layout = spec.newsletterLayout ?? 'dark-band-centered';
    if (layout === 'dark-band-centered') {
      parts.push(`NEWSLETTER — dark-band-centered: Section "w-full py-20 bg-[var(--theme-footer-bg)]". Inner "w-full max-w-2xl mx-auto px-4 flex flex-col items-center gap-6 text-center". Heading "font-bold text-[var(--theme-footer-text)] text-center". Subheading "text-[var(--theme-footer-textMuted)] text-base text-center". Row "flex flex-row gap-3 w-full max-w-md": Input flex-1 "!border-gray-600 !bg-transparent" with InputField "!text-white" + Button "!bg-[var(--theme-shop-button)] flex-none" > ButtonText "Subscribe".`);
    } else if (layout === 'two-column-split') {
      parts.push(`NEWSLETTER — two-column-split: Section "w-full py-20 bg-[var(--theme-shop-bg)]". Inner "w-full max-w-6xl mx-auto px-4 flex flex-row items-center gap-12". Left Box "flex-1 flex flex-col gap-4": Heading + Subheading "max-w-sm". Right Box "flex-1 flex flex-row gap-3": Input flex-1 "!border-gray-200" with InputField + Button "!bg-[var(--theme-shop-button)] flex-none" > ButtonText "Subscribe". Input MUST have InputField as direct child (never inside InputSlot).`);
    } else if (layout === 'minimal-inline') {
      parts.push(`NEWSLETTER — minimal-inline: Section "w-full py-10 border-t border-[var(--theme-content-textMuted)]/20 bg-[var(--theme-content-bg)]". Inner "w-full max-w-5xl mx-auto px-4 flex flex-row items-center justify-between gap-6 flex-wrap". Text "font-medium text-base text-[var(--theme-content-text)]" (heading). Row Box "flex flex-row gap-3 flex-1 max-w-sm": Input flex-1 + Button size="sm" "flex-none" > ButtonText "Join".`);
    }
  }

  if (hasTestimonials) {
    const layout = spec.testimonialsLayout ?? 'cards-dark-bg';
    if (layout === 'cards-dark-bg') {
      parts.push(`TESTIMONIALS — cards-dark-bg: Section "w-full py-20 bg-[var(--theme-footer-bg)]". Inner "w-full max-w-6xl mx-auto px-4 flex flex-col gap-10". Heading "font-bold text-[var(--theme-footer-text)] text-center". Grid "grid grid-cols-3 gap-6 w-full". Map child "contents". Each card: Box "flex flex-col gap-4 p-6 rounded-xl bg-white/10 border border-white/20" > Text "text-[var(--theme-footer-text)] text-base leading-relaxed italic" '"{{$item.review}}"' + Text "text-[var(--theme-footer-textMuted)] text-sm font-medium" "— {{$item.author}}".`);
    } else if (layout === 'large-featured') {
      parts.push(`TESTIMONIALS — large-featured (single oversized quote): Section "w-full py-24 bg-[var(--theme-content-bg)]". Inner "w-full max-w-3xl mx-auto px-4 flex flex-col items-center gap-8 text-center". Text "text-[var(--theme-shop-button)] text-7xl font-serif leading-none" "\u201c". Text "text-[var(--theme-content-text)] text-2xl font-medium leading-relaxed italic text-center" "{{testimonials.items[0].review}}". Text "text-[var(--theme-content-textMuted)] text-base font-semibold tracking-widest uppercase text-center" "— {{testimonials.items[0].author}}".`);
    }
  }

  if (hasFeatures) {
    const layout = spec.featuresLayout ?? 'icon-row';
    if (layout === 'icon-row') {
      parts.push(`FEATURES GRID — icon-row: Section "w-full py-16 bg-[var(--theme-shop-bg)]". Inner "w-full max-w-5xl mx-auto px-4 grid grid-cols-3 gap-8". 3 static Box children (NOT mapped) each "flex flex-col items-center text-center gap-3": NavIcon (icon from features[x].icon, size 32, "text-[var(--theme-shop-button)]") + Heading size="sm" "font-bold text-[var(--theme-content-text)] text-center" (features[x].title) + Text "text-[var(--theme-content-textMuted)] text-sm text-center" (features[x].description). Use content.features[0], [1], [2].`);
    } else if (layout === 'numbered-list') {
      parts.push(`FEATURES GRID — numbered-list: Section "w-full py-16 bg-[var(--theme-content-bg)]". Inner "w-full max-w-5xl mx-auto px-4 grid grid-cols-3 gap-10". 3 static Box children each "flex flex-col gap-3": Text "text-[var(--theme-shop-button)] text-5xl font-bold leading-none" "01"|"02"|"03" + Heading size="sm" "font-bold text-[var(--theme-content-text)] mt-2" (features[x].title) + Text "text-[var(--theme-content-textMuted)] text-sm leading-relaxed" (features[x].description). Use content.features[0], [1], [2].`);
    }
  }

  if (parts.length === 0) return '';

  return `\nSECTION LAYOUT TEMPLATES (use these for the sections in this brief):\n${parts.map((p, i) => `${i + 1}. ${p}`).join('\n\n')}`;
}

// ─── System prompt ────────────────────────────────────────────────────────────

function buildSystemPrompt(
  brief: DesignBrief,
  content: GeneratedContent,
  palette: Palette | null,
  fontPairing: FontPairing | null,
  spec: DesignSpec,
  retry?: StructureRetryContext,
): string {
  const paletteHint = palette
    ? `\nPALETTE (already chosen — use exactly):\nLight: ${JSON.stringify(palette.light)}\nDark: ${JSON.stringify(palette.dark)}`
    : '';

  const fontHint = fontPairing
    ? `\nFONTS (already chosen): heading="${fontPairing.heading}", body="${fontPairing.body}"`
    : '';

  const retryBlock = retry
    ? `\n\n⚠️ RETRY — FIX THESE ISSUES BEFORE ANYTHING ELSE:\n${
        retry.validatorErrors?.length
          ? `VALIDATION ERRORS:\n${retry.validatorErrors.map(e => `  - ${e}`).join('\n')}`
          : ''
      }${
        retry.qaIssues?.length
          ? `\nQA ISSUES:\n${retry.qaIssues.map(i => `  - [${i.severity.toUpperCase()}] ${i.section}: ${i.description}\n    FIX: ${i.fix}`).join('\n')}`
          : ''
      }`
    : '';

  const s = brief.sections;
  const hasProductCarousel  = s.includes('product-carousel');
  const hasFlashSale        = s.includes('flash-sale');
  const hasBrandStory       = s.includes('brand-story');
  const hasTestimonials     = s.includes('testimonials');
  const hasNewsletter       = s.includes('newsletter');
  const hasCategories       = s.includes('featured-categories');
  const hasNewArrivals      = s.includes('product-grid');
  const hasFeatures         = s.includes('features-grid');
  const hasLookbook         = s.includes('lookbook');
  const hasPressMentions    = s.includes('press-mentions');
  const hasSustainability   = s.includes('sustainability');

  // Build state conditionally — only include keys needed by the actual sections
  const prebuiltState: Record<string, unknown> = {
    hero: { heading: content.hero.heading, subheading: content.hero.subheading, imageUrl: content.hero.imageUrl },
    form: { email: '' },
  };
  // Always include featured.categories — navbar and footer always need it
  prebuiltState.featured = {
    categories: content.categories.map(c => ({ id: c.id, name: c.name, slug: c.slug, imageUrl: c.imageUrl })),
  };
  if (hasBrandStory && content.brandStory) {
    prebuiltState.brandStory = { imageUrl: content.brandStory.imageUrl };
  }
  if (hasNewArrivals && content.products?.newArrivals) {
    prebuiltState.newArrivals = { products: content.products.newArrivals };
  }
  if (hasProductCarousel && content.products?.bestSellers) {
    prebuiltState.bestSellers = { products: content.products.bestSellers };
  }
  if (hasFlashSale && content.flashSale) {
    prebuiltState.flashSale = { endsAt: content.flashSale.endsAt };
    if (content.products?.flashSaleItems) {
      prebuiltState.flashSaleProducts = { products: content.products.flashSaleItems };
    }
  }
  if (hasTestimonials && content.testimonials) {
    prebuiltState.testimonials = { items: content.testimonials.map(t => ({ id: t.id, review: t.review, author: t.author, rating: t.rating })) };
  }
  if (hasLookbook && content.lookbook) {
    prebuiltState.lookbook = { headline: content.lookbook.headline, images: content.lookbook.images };
  }

  // Build initActions only for sections actually present
  const initActions: Array<{ action: string }> = [
    { action: 'fetchNavCollections' },
    { action: 'fetchCart' },
    { action: 'fetchFeaturedCategories' },
  ];
  if (hasNewArrivals)    initActions.push({ action: 'fetchNewArrivals' });
  if (hasProductCarousel) initActions.push({ action: 'fetchBestSellers' });
  if (hasFlashSale)      initActions.push({ action: 'fetchFlashSale' });
  if (hasTestimonials)   initActions.push({ action: 'fetchTestimonials' });

  // Build content hints only for sections that have content
  const contentHints = [
    `Hero: heading="${content.hero.heading}", subheading="${content.hero.subheading}", cta="${content.hero.ctaLabel}"`,
    content.announcement ? `Announcement: "${content.announcement.text}"${content.announcement.ctaLabel ? ` CTA: "${content.announcement.ctaLabel}"` : ''}` : null,
    hasBrandStory && content.brandStory ? `Brand story: headline="${content.brandStory.headline}", body="${content.brandStory.body}", imageUrl="${content.brandStory.imageUrl}"` : null,
    hasNewsletter && content.newsletter ? `Newsletter: heading="${content.newsletter.heading}", subheading="${content.newsletter.subheading}"` : null,
    hasFlashSale && content.flashSale ? `Flash sale ends: "${content.flashSale.endsAt}", badge: "${content.flashSale.badge}"` : null,
    hasLookbook && content.lookbook ? `Lookbook: headline="${content.lookbook.headline}", images (${content.lookbook.images.length} URLs in state.lookbook.images)` : null,
    hasPressMentions && content.pressMentions ? `Press mentions: headline="${content.pressMentions.headline}", outlets: ${content.pressMentions.outlets.join(', ')}` : null,
    hasSustainability && content.sustainability ? `Sustainability: headline="${content.sustainability.headline}", body="${content.sustainability.body}"` : null,
    hasFeatures && content.features ? `Features: ${content.features.map(f => `${f.icon}: "${f.title}"`).join(', ')}` : null,
  ].filter(Boolean).join('\n');

  return `You are a senior SDUI architect. Build a complete page: content sections + navbar + footer.
Content and colors are pre-decided — DO NOT invent new copy or images.
${retryBlock}

DESIGN SPEC:
- Visual direction: ${spec.visualDirection}
- Layout style: ${spec.layoutStyle}
- Typography: ${spec.typographyStyle}
- Design mood: ${spec.designMood}
- Brand personality: ${spec.brandPersonality}

BRAND BRIEF:
- Brand: ${brief.brandName}
- Industry: ${brief.industryType}
- Tone: ${brief.brandTone}
- Sections to include (in order): ${brief.sections.join(', ')}
${paletteHint}
${fontHint}

PRE-BUILT CONTENT (use these exact values in state and text nodes):
${contentHints}

PRE-BUILT STATE (include this exactly in screen state — do NOT change field names):
${JSON.stringify(prebuiltState, null, 2)}

SDUI FIELD REFERENCE (critical — follow exactly):
- Product fields: productName (NOT name), productAsset.preview (NOT featuredAsset.preview), priceWithTax as { "__typename": "SinglePrice", "value": <cents integer> }
- Map pattern — CRITICAL: The "map" ALWAYS goes on the ITEM TEMPLATE child, NEVER on the grid/flex/row container.
  Box defaults to "flex flex-col". Putting "map" on a "grid grid-cols-4" Box renders N separate single-item grids that STACK — COMPLETELY BROKEN.
  CORRECT grid:     { "type": "Box", "props": { "className": "grid grid-cols-4 gap-6 w-full max-w-6xl mx-auto px-4" }, "children": [{ "type": "Box", "map": "items", "key": "$item.id", "props": { "className": "contents" }, "children": [<card>] }] }
  CORRECT flex row: { "type": "Box", "props": { "className": "flex flex-row gap-6 w-full max-w-6xl mx-auto px-4" }, "children": [{ "type": "Box", "map": "items", "key": "$item.id", "props": { "className": "flex-1 ..." }, "children": [...] }] }
  CORRECT stack:    { "type": "Box", "props": { "className": "flex flex-col gap-4 w-full max-w-6xl mx-auto px-4" }, "children": [{ "type": "Box", "map": "items", "key": "$item.id", "props": { "className": "..." }, "children": [...] }] }
  WRONG (NEVER):    { "type": "Box", "map": "items", "props": { "className": "grid grid-cols-4 ..." } }  ← N broken single-item grids
  WRONG (NEVER):    { "type": "Box", "map": "items", "props": { "className": "flex flex-row ..." } }  ← N broken single-item rows
  RULE: layout class (grid/flex/flex-row) belongs on the CONTAINER (no map). The map child gets "contents" (grid) or "flex-1" (row).
- Icons: { "type": "NavIcon", "props": { "icon": "ShoppingCart", "size": 20 } } — NEVER { "type": "Icon", "props": { "as": "..." } }
- CountdownTimer: { "type": "CountdownTimer", "props": { "target": "{{flashSale.endsAt}}" } } — target prop only, never targetPath
- Images: NextImage with src from state e.g. "{{$item.imageUrl}}" — NEVER local paths like /images/xxx
- Layout width: every container with mx-auto MUST also have w-full (e.g. "w-full max-w-6xl mx-auto px-4")
- Horizontal layout: Box defaults to "flex flex-col" — ALWAYS add "flex-row" explicitly for side-by-side. "flex justify-between" alone does NOT make a row; MUST write "flex flex-row justify-between".
- Heading/Text text-align: Box "text-center" does NOT cascade to Heading or Text. Add "text-center" directly on every Heading/Text that needs centering. Use "items-center" on parent Box for centering children.
- Text in views: NEVER use "text" on Pressable or Box — always wrap in { "type": "Text" } child
- Button labels: ALWAYS use ButtonText child — NEVER use "text" directly on Button
  Example: { "type": "Button", "children": [{ "type": "ButtonText", "text": "Shop Now" }] }
- Email/text Input pattern — CRITICAL (from cursor rules, this is the ONLY correct form):
  • InputField MUST be a DIRECT child of Input — NEVER nest InputField inside InputSlot
  • InputSlot is ONLY for icon slots (left/right icons) — it is NOT a wrapper for InputField
  • Always give Input "flex-1" when it's in a flex-row with a Button
  • Always pass variant="outline" and size="md" to Input
  CORRECT: { "type": "Input", "props": { "variant": "outline", "size": "md", "className": "flex-1 !rounded-md !border-gray-200" }, "children": [{ "type": "InputField", "props": { "placeholder": "Enter your email", "placeholderTextColor": "#9ca3af", "className": "!text-gray-900 dark:!text-gray-100" }, "actions": { "change": { "action": "setState", "payload": { "path": "screens.home.form.email", "value": "$event" } } } }] }
  WRONG: { "type": "Input", "children": [{ "type": "InputSlot", "children": [{ "type": "InputField" }] }] }  ← InputField inside InputSlot = field crammed to left edge
- setState path: use full screen-scoped path "screens.home.form.email" NOT short alias "form.email"
- state access: NEVER use "state." prefix in paths — access screen state DIRECTLY: use "hero.heading" NOT "state.hero.heading"; use "featured.categories" NOT "state.featured.categories"
- actions format: ALWAYS a record { "click": {...}, "change": {...} } — NEVER an array [...]
- children arrays: NEVER use null or undefined as a child — omit the entry entirely if conditional
- hero section id: ALWAYS add top-level "id": "hero-section" to the hero Box — required for validators
- hero MUST show the heading — choose ONE of the 5 heroVariants below based on spec.heroVariant:

  VARIANT A — overlay (spec.heroVariant = "overlay"): full-bleed image + gradient overlay + centered text
  { "type": "Box", "id": "hero-section", "props": { "className": "relative w-full min-h-[80vh] flex flex-col items-center justify-center overflow-hidden" }, "children": [
    { "type": "NextImage", "props": { "src": "{{hero.imageUrl}}", "alt": "Hero", "fill": true, "className": "object-cover" } },
    { "type": "Box", "props": { "className": "absolute inset-0 bg-gradient-to-t from-black/70 via-black/40 to-transparent" } },
    { "type": "Box", "props": { "className": "relative z-10 flex flex-col items-center gap-6 px-4 text-center max-w-3xl mx-auto" }, "children": [
      { "type": "Heading", "props": { "size": "4xl", "className": "text-white font-bold drop-shadow-lg text-center" }, "text": "{{hero.heading}}" },
      { "type": "Text", "props": { "className": "text-white/90 text-xl drop-shadow text-center" }, "text": "{{hero.subheading}}" },
      { "type": "Button", "props": { "className": "!bg-[var(--theme-shop-button)] !text-[var(--theme-shop-buttonText)] mt-2" }, "actions": { "click": { "action": "navigate", "payload": { "path": "/shop" } } }, "children": [{ "type": "ButtonText", "text": "{{hero.ctaLabel}}" }] }
    ]}
  ]}

  VARIANT B — split-left (spec.heroVariant = "split-left"): text left + image right, both full-height
  { "type": "Box", "id": "hero-section", "props": { "className": "w-full min-h-[80vh] flex flex-row items-stretch overflow-hidden bg-[var(--theme-hero-bg)]" }, "children": [
    { "type": "Box", "props": { "className": "flex-1 flex flex-col justify-center gap-6 px-12 md:px-16 py-16" }, "children": [
      { "type": "Heading", "props": { "size": "4xl", "className": "font-bold text-[var(--theme-content-text)] leading-tight" }, "text": "{{hero.heading}}" },
      { "type": "Text", "props": { "className": "text-[var(--theme-content-textMuted)] text-xl max-w-md" }, "text": "{{hero.subheading}}" },
      { "type": "Button", "props": { "className": "!bg-[var(--theme-shop-button)] !text-[var(--theme-shop-buttonText)] self-start mt-2" }, "actions": { "click": { "action": "navigate", "payload": { "path": "/shop" } } }, "children": [{ "type": "ButtonText", "text": "{{hero.ctaLabel}}" }] }
    ]},
    { "type": "Box", "props": { "className": "flex-1 relative min-h-[80vh]" }, "children": [
      { "type": "NextImage", "props": { "src": "{{hero.imageUrl}}", "alt": "Hero", "fill": true, "className": "object-cover" } }
    ]}
  ]}

  VARIANT C — split-right (spec.heroVariant = "split-right"): image left + bold text right
  { "type": "Box", "id": "hero-section", "props": { "className": "w-full min-h-[80vh] flex flex-row items-stretch overflow-hidden bg-[var(--theme-hero-bg)]" }, "children": [
    { "type": "Box", "props": { "className": "flex-1 relative min-h-[80vh]" }, "children": [
      { "type": "NextImage", "props": { "src": "{{hero.imageUrl}}", "alt": "Hero", "fill": true, "className": "object-cover" } }
    ]},
    { "type": "Box", "props": { "className": "flex-1 flex flex-col justify-center gap-6 px-12 md:px-16 py-16 bg-[var(--theme-hero-bg)]" }, "children": [
      { "type": "Heading", "props": { "size": "4xl", "className": "font-bold text-[var(--theme-content-text)] leading-tight" }, "text": "{{hero.heading}}" },
      { "type": "Text", "props": { "className": "text-[var(--theme-content-textMuted)] text-xl max-w-md" }, "text": "{{hero.subheading}}" },
      { "type": "Button", "props": { "className": "!bg-[var(--theme-shop-button)] !text-[var(--theme-shop-buttonText)] self-start mt-2" }, "actions": { "click": { "action": "navigate", "payload": { "path": "/shop" } } }, "children": [{ "type": "ButtonText", "text": "{{hero.ctaLabel}}" }] }
    ]}
  ]}

  VARIANT D — text-only (spec.heroVariant = "text-only"): NO image, oversized bold type on brand gradient
  { "type": "Box", "id": "hero-section", "props": { "className": "w-full min-h-[70vh] flex flex-col items-center justify-center gap-8 bg-gradient-to-br from-[var(--theme-hero-bg)] to-[var(--theme-content-bg)] px-4" }, "children": [
    { "type": "Heading", "props": { "size": "5xl", "className": "text-center font-bold text-[var(--theme-content-text)] max-w-4xl leading-tight" }, "text": "{{hero.heading}}" },
    { "type": "Text", "props": { "className": "text-[var(--theme-content-textMuted)] text-xl text-center max-w-2xl" }, "text": "{{hero.subheading}}" },
    { "type": "Box", "props": { "className": "flex flex-row gap-4 mt-2" }, "children": [
      { "type": "Button", "props": { "className": "!bg-[var(--theme-shop-button)] !text-[var(--theme-shop-buttonText)]" }, "actions": { "click": { "action": "navigate", "payload": { "path": "/shop" } } }, "children": [{ "type": "ButtonText", "text": "{{hero.ctaLabel}}" }] },
      { "type": "Button", "props": { "variant": "outline", "className": "!border-[var(--theme-content-text)] !text-[var(--theme-content-text)]" }, "actions": { "click": { "action": "navigate", "payload": { "path": "/about" } } }, "children": [{ "type": "ButtonText", "text": "Our Story" }] }
    ]}
  ]}

  VARIANT E — asymmetric (spec.heroVariant = "asymmetric"): text card floats bottom-left over full-bleed image
  { "type": "Box", "id": "hero-section", "props": { "className": "relative w-full min-h-[85vh] overflow-hidden" }, "children": [
    { "type": "NextImage", "props": { "src": "{{hero.imageUrl}}", "alt": "Hero", "fill": true, "className": "object-cover object-top" } },
    { "type": "Box", "props": { "className": "absolute inset-0 bg-gradient-to-r from-black/60 via-black/20 to-transparent" } },
    { "type": "Box", "props": { "className": "absolute bottom-12 left-8 md:left-16 max-w-lg flex flex-col gap-4" }, "children": [
      { "type": "Heading", "props": { "size": "4xl", "className": "text-white font-bold drop-shadow-lg" }, "text": "{{hero.heading}}" },
      { "type": "Text", "props": { "className": "text-white/90 text-lg drop-shadow" }, "text": "{{hero.subheading}}" },
      { "type": "Button", "props": { "className": "!bg-[var(--theme-shop-button)] !text-[var(--theme-shop-buttonText)] self-start" }, "actions": { "click": { "action": "navigate", "payload": { "path": "/shop" } } }, "children": [{ "type": "ButtonText", "text": "{{hero.ctaLabel}}" }] }
    ]}
  ]}

- spec.heroVariant = "${spec.heroVariant}" — USE THIS VARIANT for the hero section
- hero heading "{{hero.heading}}" MUST be visible in the hero — never hidden, never missing, never outside the hero section
- content order: if announcement bar is included, it is FIRST child (index 0), hero-section is SECOND (index 1). If no announcement, hero-section is FIRST. Hero MUST precede all product/category sections.
- announcement bar position: ALWAYS before hero (top strip), NEVER after hero
- announcement bar MUST include an X dismiss button on the right edge:
  { "type": "Box", "props": { "className": "w-full bg-[var(--theme-announcement-bg)] py-2 px-4 flex flex-row items-center justify-between" }, "children": [
    { "type": "Box", "props": { "className": "flex-1" } },
    { "type": "Text", "props": { "className": "flex-1 text-[var(--theme-announcement-text)] text-sm text-center" }, "text": "Your promo message here" },
    { "type": "Pressable", "props": { "className": "flex-none" }, "actions": { "click": { "action": "setState", "payload": { "path": "screens.home.announcementDismissed", "value": true } } }, "children": [
      { "type": "Text", "props": { "className": "text-[var(--theme-announcement-text)] text-lg leading-none px-2" }, "text": "×" }
    ]}
  ]}
- price display — ALWAYS use formatCurrency with expr wrapper (only correct form):
  { "type": "Text", "text": { "expr": { "formatCurrency": [{ "var": "$item.priceWithTax.value" }, 100] } } }
  • The "expr" wrapper is MANDATORY — without it, raw JSON appears on screen
  • NEVER: "{{$item.currencyCode}} {{$item.priceWithTax.value}}" — prints "USD 2999" (raw cents, wrong)
  • NEVER: "{{$item.priceWithTax.value}}" alone — prints "2999" (raw cents, no currency symbol)
  • NEVER: { "formatCurrency": [...] } without the "expr" wrapper — shows raw JSON object on screen

VISUAL DESIGN RULES (non-negotiable — every violation makes the page look broken/amateurish):

1. NextImage fill=true ALWAYS needs a relative+height parent
   WRONG: { "type": "Box", "props": { "className": "flex flex-col" }, "children": [{ "type": "NextImage", "props": { "fill": true } }] }
   RIGHT: { "type": "Box", "props": { "className": "relative w-full h-52" }, "children": [{ "type": "NextImage", "props": { "fill": true, "className": "object-cover" } }] }
   — WITHOUT this the image renders at 0px height and is COMPLETELY INVISIBLE

2. Category cards — Pressable does NOT apply h-48 as height (RN-based, collapses to content).
   WRONG: { "type": "Pressable", "props": { "className": "relative h-48 flex items-end ..." }, "children": [NextImage...] }  ← Pressable ignores h-48, card = 30px tall
   RIGHT: Pressable is the clickable wrapper (no height). Image height lives on inner Box:
   { "type": "Pressable", "props": { "className": "block rounded-xl overflow-hidden hover:opacity-90" }, "actions": {...}, "children": [
     { "type": "Box", "props": { "className": "relative w-full h-48" }, "children": [
       { "type": "NextImage", "props": { "src": "{{$item.imageUrl}}", "fill": true, "className": "object-cover" } },
       { "type": "Box", "props": { "className": "absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" } },
       { "type": "Box", "props": { "className": "absolute bottom-0 left-0 right-0 p-3" }, "children": [
         { "type": "Text", "props": { "className": "text-white font-bold text-lg text-center" }, "text": "{{$item.name}}" }
       ]}
     ]}
   ]}

3. Product cards MUST use a relative+height image container
   Template: outer Box "flex flex-col rounded-xl overflow-hidden shadow-sm" → inner "relative w-full h-52" → NextImage fill → p-3 Box for text

4. Map + layout: layout class goes on the CONTAINER (no map). map goes on the ITEM inside the container.
   The renderer creates N copies of the mapped node as siblings. If you put "grid grid-cols-4" on the mapped node, you get N separate grids each with 1 card — they all stack vertically.
   WRONG: { "map": "items", "props": { "className": "grid grid-cols-4 gap-6 max-w-6xl mx-auto" } }  ← N broken grids
   WRONG: { "map": "items", "props": { "className": "flex flex-row gap-6 max-w-6xl mx-auto" } }  ← N broken rows
   RIGHT (grid): { "props": { "className": "grid grid-cols-4 gap-6 w-full max-w-6xl mx-auto px-4" }, "children": [{ "map": "items", "props": { "className": "contents" }, "children": [<card>] }] }
   RIGHT (row):  { "props": { "className": "flex flex-row gap-6 w-full max-w-6xl mx-auto px-4" }, "children": [{ "map": "items", "props": { "className": "flex-1 p-6 ..." }, "children": [...] }] }
   The "w-full max-w-6xl mx-auto px-4" always belongs on the CONTAINER, never on the mapped child.

5. Section padding MUST be py-16 md:py-20 minimum (never py-8 for main sections)
   py-8 looks cramped. py-16 md:py-20 is the minimum for premium feel. py-24 md:py-32 for hero-sized sections.

6. Alternate section backgrounds — NEVER same bg-[var(--theme-content-bg)] for all sections
   Pattern: content-bg → shop-bg → content-bg → accent section (dark or color) → content-bg
   Use a dark or brand-colored background for the newsletter/CTA section

7. Announcement bar goes BEFORE hero (section index 0), hero is index 1
   NEVER place announcement after hero — it looks like an afterthought

8. Brand story layout — CHOOSE ONE based on the design spec (do NOT always do split):
   OPTION A — Split (image left + text right): use when the spec calls for editorial or warm feel
     Container: "w-full max-w-6xl mx-auto px-4 flex flex-col md:flex-row items-center gap-12"
     Left pane: "flex-1 relative h-80 rounded-2xl overflow-hidden" → NextImage fill object-cover
     Right pane: "flex-1 flex flex-col gap-6" → Heading + Text (always add "gap-6" so text doesn't touch image)
   OPTION B — Text manifesto (no image): use for bold/minimalist/editorial brands
     Full-width centered section with oversized heading + body text, optionally on a dark or accent bg
   OPTION C — Full-bleed image with quote overlay: image fills section, text card positioned bottom-left
     "relative w-full min-h-[60vh] overflow-hidden" → NextImage fill → absolute card "bottom-8 left-8 max-w-lg bg-white/90 p-8 rounded-xl"

9. Sections MUST be visually distinct — use: full-bleed hero image, split layouts, asymmetric grids,
   dark CTA bands, card grids with shadows — NEVER just stacked text blocks

SECTION LAYOUT DIRECTIVES — Design Director chose these for this brand:
- productGridLayout="${spec.productGridLayout}" — use for product-grid and product-carousel sections
- categoryLayout="${spec.categoryLayout}" — use for featured-categories
- newsletterLayout="${spec.newsletterLayout}" — use for newsletter
- testimonialsLayout="${spec.testimonialsLayout}" — use for testimonials
- featuresLayout="${spec.featuresLayout}" — use for features-grid
${buildSectionTemplates(s, spec)}

10. NEW SECTION TEMPLATES — use when these sections appear in the brief:

   LOOKBOOK section — editorial lifestyle grid:
   { "type": "Box", "props": { "className": "w-full py-16 md:py-20 bg-[var(--theme-content-bg)]" }, "children": [
     { "type": "Box", "props": { "className": "w-full max-w-7xl mx-auto px-4 flex flex-col gap-8" }, "children": [
       { "type": "Heading", "props": { "size": "2xl", "className": "font-bold text-center text-[var(--theme-content-text)]" }, "text": "{{lookbook.headline}}" },
       { "type": "Box", "props": { "className": "grid grid-cols-3 gap-3 w-full" }, "children": [
         { "type": "Box", "map": "lookbook.images", "key": "$item", "props": { "className": "contents" }, "children": [
           { "type": "Box", "props": { "className": "relative w-full h-64 rounded-lg overflow-hidden" }, "children": [
             { "type": "NextImage", "props": { "src": "{{$item}}", "alt": "Lookbook", "fill": true, "className": "object-cover hover:scale-105 transition-transform duration-300" } }
           ]}
         ]}
       ]}
     ]}
   ]}

   PRESS MENTIONS section — "As seen in" logo strip:
   { "type": "Box", "props": { "className": "w-full py-12 bg-[var(--theme-shop-bg)]" }, "children": [
     { "type": "Box", "props": { "className": "w-full max-w-5xl mx-auto px-4 flex flex-col items-center gap-8" }, "children": [
       { "type": "Text", "props": { "className": "text-[var(--theme-content-textMuted)] text-sm uppercase tracking-widest text-center" }, "text": "As Seen In" },
       { "type": "Box", "props": { "className": "flex flex-row flex-wrap justify-center items-center gap-8 w-full" }, "children": [
         /* For each outlet name, render a Text node with the outlet name styled as a logo */
         { "type": "Text", "props": { "className": "text-[var(--theme-content-textMuted)] text-xl font-semibold tracking-tight opacity-60 hover:opacity-100 transition-opacity" }, "text": "Vogue" },
         { "type": "Text", "props": { "className": "text-[var(--theme-content-textMuted)] text-xl font-semibold tracking-tight opacity-60 hover:opacity-100 transition-opacity" }, "text": "Forbes" }
         /* ... more outlet Text nodes */
       ]}
     ]}
   ]}

   SUSTAINABILITY section — brand values / eco:
   { "type": "Box", "props": { "className": "w-full py-20 bg-[var(--theme-content-bg)]" }, "children": [
     { "type": "Box", "props": { "className": "w-full max-w-4xl mx-auto px-4 flex flex-col items-center gap-8 text-center" }, "children": [
       { "type": "NavIcon", "props": { "icon": "Leaf", "size": 48, "className": "text-[var(--theme-shop-button)]" } },
       { "type": "Heading", "props": { "size": "3xl", "className": "font-bold text-[var(--theme-content-text)] text-center" }, "text": "Sustainability headline here" },
       { "type": "Text", "props": { "className": "text-[var(--theme-content-textMuted)] text-lg leading-relaxed text-center max-w-2xl" }, "text": "Sustainability body here" }
     ]}
   ]}

initActions RULE — CRITICAL: Every "map": "path.items" in content MUST have a matching fetch action:
  featured.categories       → { "action": "fetchFeaturedCategories" }
  newArrivals.products      → { "action": "fetchNewArrivals" }
  bestSellers.products      → { "action": "fetchBestSellers" }
  flashSaleProducts.products → { "action": "fetchFlashSale" }
  testimonials.items        → { "action": "fetchTestimonials" }
  Always include fetchNavCollections and fetchCart. Add ALL data-loader actions for sections you include.

OUTPUT SHAPE:
{
  "meta": { "title": "<Brand> | Homepage" },
  "state": { /* pre-built state above — copy exactly */ },
  "layout": "store",
  "content": {
    "type": "Box",
    "props": { "className": "w-full flex flex-col" },
    "children": [
      /* sections in brief.sections order — vary layouts: full-bleed, split, asymmetric grid, etc.
         Let the design spec drive the visual approach for each section */
    ]
  },
  "initActions": ${JSON.stringify(initActions, null, 2)},
  "themeHint": {
    "designMood": "${spec.designMood}",
    "palette": {
      "light": { "primary": "...", "secondary": "...", "accent": "...", "background": "...", "textPrimary": "...", "textSecondary": "..." },
      "dark": { "primary": "...", "secondary": "...", "accent": "...", "background": "...", "textPrimary": "...", "textSecondary": "..." }
    },
    "fonts": { "heading": "${fontPairing?.heading ?? 'geist'}", "body": "${fontPairing?.body ?? 'geist'}" }
  },
  "layoutParts": {
    "navbar": { "structure": { /* REQUIRED: full navbar SDUI tree per NAVBAR RULES — MUST always be present */ } },
    "footer": { "structure": { /* REQUIRED: full footer SDUI tree per FOOTER RULES — MUST always be present */ } }
  }
}

⚠️ BOTH navbar and footer in layoutParts are REQUIRED. Never omit footer. A page without a footer is incomplete.

${NAVBAR_RULES}

${FOOTER_RULES}

${buildDesignPrinciplesContext()}

${buildTechPatternsContext()}

THEME VARS AVAILABLE:
- --theme-announcement-bg / --theme-announcement-text
- --theme-header-bg / --theme-header-text / --theme-header-border
- --theme-hero-bg / --theme-hero-text
- --theme-content-bg / --theme-content-text / --theme-content-textMuted
- --theme-shop-button / --theme-shop-buttonHover / --theme-shop-buttonText
- --theme-footer-bg / --theme-footer-text / --theme-footer-textMuted

${buildThemeContext()}

SDUI REFERENCE:
${buildSduiReference()}

${buildCorrectionsContext('page')}

${buildFewShotExamples()}

RULES:
- Output valid JSON only — no markdown, no comments
- Be creative with section layouts based on the design spec — vary between full-bleed, split, contained grid, and asymmetric layouts
- State must include exactly the pre-built state keys above — do NOT change field names, do NOT add extra keys
- Hero heading and subheading must match pre-built content exactly (no paraphrasing)
- Do NOT include footer or navbar inside "content" — they go in layoutParts only
- themeHint.palette must have ALL 6 keys in both light and dark
- IMAGES: Never use local paths — only Unsplash URLs from pre-built state`;
}

// ─── Agent ────────────────────────────────────────────────────────────────────

/**
 * Run the Structure Agent to build a complete SDUI page (content + navbar + footer).
 */
export async function runStructureAgent(
  brief: DesignBrief,
  content: GeneratedContent,
  palette: Palette | null,
  fontPairing: FontPairing | null,
  spec: DesignSpec,
  retry?: StructureRetryContext,
): Promise<PageGeneratorOutput> {
  const systemPrompt = buildSystemPrompt(brief, content, palette, fontPairing, spec, retry);

  const userPrompt = `Build a complete SDUI page for ${brief.brandName} — a ${brief.industryType} brand with ${brief.brandTone} tone.
Sections: ${brief.sections.join(' → ')}
Use ALL pre-built content and state values provided. Generate navbar and footer in layoutParts.`;

  const { output } = await generateText({
    model: openai('gpt-4o'),
    temperature: 1.1,
    system: systemPrompt,
    prompt: userPrompt,
    output: Output.json(),
  });

  const parsed = pageGeneratorOutputSchema.safeParse(output);
  if (!parsed.success) {
    throw new Error(`StructureAgent: Invalid output schema — ${parsed.error.message}`);
  }

  return parsed.data;
}

// ─── Compact variant-selection agent (new architecture) ───────────────────────

/**
 * Compact Structure Agent output — only picks variant IDs + fills slots.
 * The actual JSON is assembled by SectionLibrary.instantiate().
 *
 * AI input: ~400 tokens (manifest + brief)
 * AI output: ~100 tokens (variant list)
 * vs. old approach: 800+ tokens output of raw JSON
 */
export interface CompactStructureOutput {
  /** Ordered section selections */
  sections: SectionSelection[];
  /** Theme and font hints (same as before) */
  themeHint: {
    designMood: string;
    palette?: {
      light?: Record<string, string>;
      dark?: Record<string, string>;
    };
    fonts?: { heading?: string; body?: string };
  };
}

const compactOutputSchema = z.object({
  sections: z.array(z.object({
    variantId: z.string().describe('Exact variantId from the manifest e.g. "hero.overlay-centered"'),
    params: z.record(z.string(), z.string()).optional().describe('Slot values e.g. { "CTA_PATH": "/shop", "SECTION_TITLE": "New Arrivals" }'),
  })),
  themeHint: z.object({
    designMood: z.string(),
    palette: z.object({
      light: z.record(z.string(), z.string()).optional(),
      dark: z.record(z.string(), z.string()).optional(),
    }).optional(),
    fonts: z.object({
      heading: z.string().optional(),
      body: z.string().optional(),
    }).optional(),
  }),
});

/**
 * Run the compact Structure Agent: pick variants from manifest, fill slots.
 * Does NOT generate SDUI JSON — that's done by SectionLibrary.instantiate().
 */
export async function runStructureAgentCompact(
  brief: DesignBrief,
  content: GeneratedContent,
  palette: Palette | null,
  fontPairing: FontPairing | null,
  spec: DesignSpec,
): Promise<CompactStructureOutput> {
  const manifestContext = buildManifestContext();

  const paletteHint = palette
    ? `\nPALETTE (already chosen):\nLight: ${JSON.stringify(palette.light)}\nDark: ${JSON.stringify(palette.dark)}`
    : '';

  const fontHint = fontPairing
    ? `\nFONTS: heading="${fontPairing.heading}", body="${fontPairing.body}"`
    : '';

  const systemPrompt = `You are an SDUI page architect. Your job is ONLY to select section variants from the library manifest.
DO NOT generate any SDUI JSON. Just pick variant IDs and fill slot values.

${manifestContext}

SELECTION RULES:
- Match variantId exactly as shown in the manifest
- Pick ONE variant per section in the brief
- Fill slot values based on the brand content provided
- CTA_PATH should be "/shop" for products, "/about" for brand story, "/collection/<slug>" for categories
- SECTION_TITLE should be brand-appropriate (e.g. "New Arrivals", "Our Story", "Best Sellers")
- For announcement-bar: no slots needed
- For newsletter: no slots needed
- If a section type from the brief has no matching variant in the library, skip it

DESIGN SPEC:
- Visual direction: ${spec.visualDirection}
- Layout style: ${spec.layoutStyle}
- Design mood: ${spec.designMood}
- Brand personality: ${spec.brandPersonality}
- heroVariant: ${spec.heroVariant}

BRAND BRIEF:
- Brand: ${brief.brandName}
- Industry: ${brief.industryType}
- Tone: ${brief.brandTone}
- Sections to include (in order): ${brief.sections.join(', ')}

PRE-BUILT CONTENT REFERENCE:
- Hero: heading="${content.hero.heading}", cta="${content.hero.ctaLabel}"
- Categories: ${content.categories.slice(0, 3).map(c => c.name).join(', ')}
- Products: ${content.products?.newArrivals?.slice(0, 3).map(p => p.productName).join(', ') ?? 'none'}
${paletteHint}${fontHint}`;

  const { object } = await generateObject({
    model: openai('gpt-4o-mini'),
    temperature: 0.8,
    system: systemPrompt,
    prompt: `Select section variants for ${brief.brandName} (${brief.brandTone} ${brief.industryType} brand).
Sections to cover: ${brief.sections.join(' → ')}`,
    schema: compactOutputSchema,
  });

  return object;
}
