/**
 * Valid component type values for UI nodes.
 * Keep in sync with lib/sdui/component-registry.tsx — run `npm run check:component-sync` to verify.
 * Used by schema and AI generators.
 */

export const COMPONENT_NAMES = [
  'Box',
  'Text',
  'HStack',
  'VStack',
  'Center',
  'Grid',
  'GridItem',
  'Heading',
  'Spinner',
  'Image',
  'HtmlContent',
  'Input',
  'Tooltip',
  'TooltipContent',
  'TooltipText',
  'Checkbox',
  'CheckboxGroup',
  'CheckboxIndicator',
  'CheckboxLabel',
  'Switch',
  'Textarea',
  'TextareaInput',
  'Skeleton',
  'SkeletonText',
  'ScrollView',
  'SafeAreaView',
  'Icon',
  'Video',
  'Carousel',
  'CarouselSlide',
  'Accordion',
  'AccordionItem',
  'AccordionHeader',
  'AccordionTrigger',
  'AccordionContent',
  'Select',
  'SelectTrigger',
  'SelectInput',
  'SelectPortal',
  'SelectBackdrop',
  'SelectContent',
  'SelectDragIndicator',
  'SelectDragIndicatorWrapper',
  'SelectItem',
  'SelectScrollView',
  'SelectVirtualizedList',
  'SelectFlatList',
  'SelectSectionList',
  'SelectSectionHeaderText',
  'Radio',
  'RadioGroup',
  'RadioIndicator',
  'RadioLabel',
  'Progress',
  'ProgressFilledTrack',
  'Slider',
  'SliderThumb',
  'SliderTrack',
  'SliderFilledTrack',
  'CountdownTimer',
] as const;
