/**
 * NavIcon and icon mapping - Lucide icons for SDUI JSON
 */

import React from 'react';
import {
  Search,
  User,
  ShoppingBag,
  Menu as MenuIcon,
  Share,
  Globe,
  Heart,
  Check,
  CheckCircle2,
  CircleDollarSign,
  Zap,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Bell,
  Star,
  Package,
  Truck,
  ShieldCheck,
  X,
  Plus,
  Minus,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  LogOut,
  LogIn,
  Sun,
  Moon,
  Monitor,
  ShoppingCart,
  Tag,
  Home,
  Settings,
  Mail,
  Image,
  Eye,
  EyeOff,
  TrendingUp,
  TrendingDown,
  Inbox,
  Upload,
  Download,
  ExternalLink,
  Link,
  Lock,
  Unlock,
  Filter,
  Pencil,
  PenLine,
  Trash,
  Trash2,
  Copy,
  Calendar,
  Clock,
  MapPin,
  Map,
  Phone,
  Info,
  AlertCircle,
  AlertTriangle,
  HelpCircle,
  RefreshCw,
  Loader,
  LayoutGrid,
  List,
  Layers,
  Code,
  FileText,
  File,
  Folder,
  Camera,
  Video,
  Music,
  Wifi,
  Bluetooth,
  Battery,
  Power,
  Flag,
  Bookmark,
  Maximize,
  Minimize,
  MoreHorizontal,
  MoreVertical,
  Send,
  MessageCircle,
  MessageSquare,
  Smile,
  Award,
  Gift,
  Coffee,
  Briefcase,
  Building,
  Users,
  UserPlus,
  UserCheck,
  CreditCard,
  DollarSign,
  Percent,
  ChartBar,
  ChartPie,
  Activity,
  SlidersHorizontal,
  ToggleLeft,
  ToggleRight,
  SquareCheck,
  Circle,
  Square,
} from 'lucide-react-native';

export const NAV_ICONS: Record<string, React.ComponentType<{ size?: number; color?: string; strokeWidth?: number; className?: string }>> = {
  // Navigation & Layout
  Home,
  Menu: MenuIcon,
  Settings,
  LayoutGrid,
  List,
  Layers,
  Maximize,
  Minimize,
  MoreHorizontal,
  MoreVertical,
  Filter,
  // User & Auth
  User,
  Users,
  UserPlus,
  UserCheck,
  LogIn,
  LogOut,
  Lock,
  Unlock,
  // Communication
  Bell,
  Mail,
  Send,
  MessageCircle,
  MessageSquare,
  Phone,
  Inbox,
  // E-commerce
  ShoppingCart,
  ShoppingBag,
  Package,
  Tag,
  CreditCard,
  DollarSign,
  CircleDollarSign,
  Percent,
  Truck,
  // Actions
  Search,
  Plus,
  Minus,
  X,
  Check,
  CheckCircle2,
  SquareCheck,
  Pencil,
  PenLine,
  Trash,
  Trash2,
  Copy,
  Upload,
  Download,
  RefreshCw,
  ExternalLink,
  Link,
  Share,
  // Media
  Image,
  Camera,
  Video,
  Music,
  Eye,
  EyeOff,
  // Arrows & Chevrons
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  // Indicators & Status
  Star,
  Heart,
  Favourite: Heart,
  Bookmark,
  Flag,
  Award,
  Zap,
  ShieldCheck,
  AlertCircle,
  AlertTriangle,
  HelpCircle,
  Info,
  Loader,
  TrendingUp,
  TrendingDown,
  Activity,
  // Data & Charts
  ChartBar,
  ChartPie,
  SlidersHorizontal,
  ToggleLeft,
  ToggleRight,
  // Date & Time
  Calendar,
  Clock,
  // Location
  MapPin,
  Map,
  Globe,
  // Files & Code
  FileText,
  File,
  Folder,
  Code,
  // Theme
  Sun,
  Moon,
  Monitor,
  // Misc
  Coffee,
  Gift,
  Smile,
  Briefcase,
  Building,
  Battery,
  Bluetooth,
  Wifi,
  Power,
  Circle,
  Square,
};

export const NAMED_SIZE_MAP: Record<string, number> = {
  '2xs': 12,
  xs: 14,
  sm: 16,
  md: 18,
  lg: 20,
  xl: 24,
};

type NavIconProps = {
  icon: string;
  size?: number | string;
  color?: string;
  className?: string;
  [k: string]: unknown;
};

/**
 * Renders a Lucide icon by name.
 * Uses forwardRef so the builder can attach data-builder-id via a ref callback.
 * The ref lands on a wrapping inline-flex span (invisible to layout, supports setAttribute).
 */
export const NavIcon = React.forwardRef<HTMLSpanElement, NavIconProps>(
  function NavIcon(props, ref) {
    const { icon, size = 'sm', color, className, ...rest } = props;
    const IconComponent = icon ? NAV_ICONS[icon as keyof typeof NAV_ICONS] : null;
    if (!IconComponent) return null;
    const numericSize = typeof size === 'number' ? size : (NAMED_SIZE_MAP[size as string] ?? 16);
    return (
      <span ref={ref} className="inline-flex items-center justify-center">
        <IconComponent size={numericSize} color={color as string} className={className as string} {...(rest as object)} />
      </span>
    );
  }
);
